-- pgddl_tools--1.0.0.sql
-- Utilities for reconstructing common PostgreSQL DDL from system catalogs.

CREATE SCHEMA IF NOT EXISTS pgddl_tools;

CREATE OR REPLACE FUNCTION pgddl_tools.quote_qualified_name(object_oid oid)
RETURNS text
LANGUAGE sql
STABLE
PARALLEL SAFE
AS $$
    SELECT quote_ident(n.nspname) || '.' || quote_ident(c.relname)
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.oid = object_oid;
$$;

CREATE OR REPLACE FUNCTION pgddl_tools.relation_kind(relation_oid oid)
RETURNS text
LANGUAGE sql
STABLE
PARALLEL SAFE
AS $$
    SELECT CASE c.relkind
        WHEN 'r' THEN 'TABLE'
        WHEN 'p' THEN 'PARTITIONED TABLE'
        WHEN 'f' THEN 'FOREIGN TABLE'
        WHEN 'v' THEN 'VIEW'
        WHEN 'm' THEN 'MATERIALIZED VIEW'
        WHEN 'S' THEN 'SEQUENCE'
        WHEN 'i' THEN 'INDEX'
        WHEN 'I' THEN 'PARTITIONED INDEX'
        ELSE c.relkind::text
    END
    FROM pg_class c
    WHERE c.oid = relation_oid;
$$;

CREATE OR REPLACE FUNCTION pgddl_tools.get_table_columns(relation_oid oid)
RETURNS text
LANGUAGE sql
STABLE
AS $$
    SELECT string_agg(
        '    ' || quote_ident(a.attname) || ' ' || pg_catalog.format_type(a.atttypid, a.atttypmod) ||
        CASE WHEN a.attidentity <> '' THEN
            CASE a.attidentity WHEN 'a' THEN ' GENERATED ALWAYS AS IDENTITY' ELSE ' GENERATED BY DEFAULT AS IDENTITY' END
        ELSE '' END ||
        CASE WHEN a.attgenerated = 's' THEN ' GENERATED ALWAYS AS (' || pg_get_expr(ad.adbin, ad.adrelid) || ') STORED'
             WHEN ad.adbin IS NOT NULL AND a.attidentity = '' THEN ' DEFAULT ' || pg_get_expr(ad.adbin, ad.adrelid)
             ELSE '' END ||
        CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END ||
        CASE WHEN col_description(a.attrelid, a.attnum) IS NOT NULL THEN ' /* ' || replace(col_description(a.attrelid, a.attnum), '*/', '* /') || ' */' ELSE '' END,
        E',\n' ORDER BY a.attnum
    )
    FROM pg_attribute a
    LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
    WHERE a.attrelid = relation_oid
      AND a.attnum > 0
      AND NOT a.attisdropped;
$$;

CREATE OR REPLACE FUNCTION pgddl_tools.get_table_constraints(relation_oid oid)
RETURNS text
LANGUAGE sql
STABLE
AS $$
    SELECT string_agg('    CONSTRAINT ' || quote_ident(conname) || ' ' || pg_get_constraintdef(oid, true), E',\n' ORDER BY conname)
    FROM pg_constraint
    WHERE conrelid = relation_oid
      AND contype IN ('p', 'u', 'c', 'f', 'x');
$$;

CREATE OR REPLACE FUNCTION pgddl_tools.get_indexes(relation_oid oid)
RETURNS SETOF text
LANGUAGE sql
STABLE
AS $$
    SELECT pg_get_indexdef(i.indexrelid) || ';'
    FROM pg_index i
    JOIN pg_class idx ON idx.oid = i.indexrelid
    WHERE i.indrelid = relation_oid
      AND NOT i.indisprimary
      AND NOT EXISTS (
          SELECT 1
          FROM pg_constraint con
          WHERE con.conindid = i.indexrelid
      )
    ORDER BY idx.relname;
$$;


CREATE OR REPLACE FUNCTION pgddl_tools.format_fdw_options(options text[])
RETURNS text
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$
    SELECT COALESCE(
        (
            SELECT ' OPTIONS (' || string_agg(
                quote_ident(split_part(option_text, '=', 1)) || ' ' || quote_literal(substr(option_text, strpos(option_text, '=') + 1)),
                ', ' ORDER BY option_text
            ) || ')'
            FROM unnest(options) AS option_text
        ),
        ''
    );
$$;

CREATE OR REPLACE FUNCTION pgddl_tools.get_relation_ddl(relation regclass, include_indexes boolean DEFAULT true)
RETURNS text
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    rel_oid oid := relation::oid;
    rel_record record;
    columns_sql text;
    constraints_sql text;
    body_sql text;
    ddl text;
    index_sql text;
    foreign_server_sql text;
BEGIN
    SELECT c.*, n.nspname
    INTO rel_record
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE c.oid = rel_oid;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'relation % does not exist', relation;
    END IF;

    IF rel_record.relkind = 'v' THEN
        RETURN 'CREATE OR REPLACE VIEW ' || pgddl_tools.quote_qualified_name(rel_oid) || ' AS' || E'\n' || pg_get_viewdef(rel_oid, true) || ';';
    ELSIF rel_record.relkind = 'm' THEN
        RETURN 'CREATE MATERIALIZED VIEW ' || pgddl_tools.quote_qualified_name(rel_oid) || ' AS' || E'\n' || pg_get_viewdef(rel_oid, true) || E'\nWITH NO DATA;';
    ELSIF rel_record.relkind NOT IN ('r', 'p', 'f') THEN
        RAISE EXCEPTION 'relation % has unsupported relkind %', relation, rel_record.relkind;
    END IF;

    columns_sql := pgddl_tools.get_table_columns(rel_oid);
    constraints_sql := pgddl_tools.get_table_constraints(rel_oid);
    body_sql := concat_ws(E',\n', columns_sql, constraints_sql);

    ddl := 'CREATE ' || CASE WHEN rel_record.relkind = 'f' THEN 'FOREIGN TABLE' ELSE 'TABLE' END || ' ' || pgddl_tools.quote_qualified_name(rel_oid) || E' (\n' || body_sql || E'\n)';

    IF rel_record.relkind = 'f' THEN
        SELECT ' SERVER ' || quote_ident(srv.srvname) || pgddl_tools.format_fdw_options(ft.ftoptions)
        INTO foreign_server_sql
        FROM pg_foreign_table ft
        JOIN pg_foreign_server srv ON srv.oid = ft.ftserver
        WHERE ft.ftrelid = rel_oid;

        ddl := ddl || foreign_server_sql;
    END IF;

    IF rel_record.relkind = 'p' THEN
        ddl := ddl || E'\n' || pg_get_partkeydef(rel_oid);
    END IF;

    ddl := ddl || ';';

    IF include_indexes THEN
        FOR index_sql IN SELECT * FROM pgddl_tools.get_indexes(rel_oid) LOOP
            ddl := ddl || E'\n\n' || index_sql;
        END LOOP;
    END IF;

    RETURN ddl;
END;
$$;

CREATE OR REPLACE FUNCTION pgddl_tools.get_schema_ddl(schema_name name, include_indexes boolean DEFAULT true)
RETURNS text
LANGUAGE sql
STABLE
AS $$
    SELECT string_agg(pgddl_tools.get_relation_ddl(c.oid::regclass, include_indexes), E'\n\n' ORDER BY c.relkind, c.relname)
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = schema_name
      AND c.relkind IN ('r', 'p', 'f', 'v', 'm');
$$;

COMMENT ON SCHEMA pgddl_tools IS 'Utilities for inspecting PostgreSQL object DDL';
COMMENT ON FUNCTION pgddl_tools.get_relation_ddl(regclass, boolean) IS 'Return reconstructed DDL for a table, foreign table, partitioned table, view, or materialized view.';
COMMENT ON FUNCTION pgddl_tools.get_schema_ddl(name, boolean) IS 'Return reconstructed DDL for supported relations in a schema.';
